/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  
  tutorialSidebar: [
    'intro',
	{
		type: 'category',
		label: 'C',
		items: [
		'C/introduzione',
		'C/variabili',
		'C/if',
		'C/switch',
		'C/for',
		'C/do-while',
		'C/array',
		'C/struct',
		],
	},

    {
      type: 'category',
      label: 'C++',
	  // link: {
      //   type: 'generated-index',
      // },
      items: [
		'C++/introduzione',
		'C++/variabili',
		'C++/if',
		'C++/switch',
		'C++/for',
		'C++/while',
		'C++/do-while',
		'C++/array',
		'C++/vettori',
		'C++/stringhe',
		'C++/struct',
	  ],
    },

	{
		type: 'category',
		label: 'Java',
		// link: {
		//   type: 'generated-index',
		// },
		items: [
		  'Java/introduzione',
		  'Java/variabili',
		  'Java/if',
		  'Java/switch',
		  'Java/for',
		  'Java/while',
		  'Java/do-while',
		  'Java/array',
		  'Java/string',
		],
	  },

	{
		type: 'category',
		label: 'Python',
		items: [
		'Python/comment',
		'Python/for',
		'Python/while',
		'Python/liste',
		'Python/tuple',
		],
	},

	
  ],
   
};

module.exports = sidebars;
